#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import offsetbox
import pickle
from sklearn import manifold


loadfile = 'learn_evolve'
iter = '1002'
perplexity = 50
n_iter = 1000

def upper_tri_masking(A):
    m = A.shape[0]
    r = np.arange(m)
    mask = r[:,None] < r
    return A[mask]

folder = 'save/' + loadfile

# filename = 'save/' + loadfile + '/isings/gen[' + iter + ']-isings.pickle'

# startstr = 'Loading simulation:' + filename
# print(startstr)

# isings = pickle.load(open(filename, 'rb'))

FOOD = []
for iter in np.arange(0, 1002, 25):
    filename = 'save/' + loadfile + '/isings/gen[' + str(iter) + ']-isings.pickle'

    startstr = 'Loading simulation:' + filename
    print(startstr)

    isings = pickle.load(open(filename, 'rb'))

    food = []
    for i, I in enumerate(isings):
        food.append(I.fitness)

    FOOD.append(np.sum(food))



plt.plot(FOOD,'.')
plt.title('')
plt.xlabel('Generations')
plt.ylabel('Food')

plt.show()
print()
