#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import pickle

loadfile = 'sim-20180430-215748'
iter_list = np.arange(0, 1104, 1)
numAgents = 50

Beta = np.zeros((numAgents, len(iter_list)))


for i, iter in enumerate(iter_list):
    filename = 'save/' + loadfile + '/isings/gen[' + str(iter) + ']-isings.pickle'

    startstr = 'Loading simulation:' + filename
    print(startstr)

    isings = pickle.load(open(filename, 'rb'))

    for orgNum, I in enumerate(isings):
        Beta[orgNum, i] = I.Beta

fig, ax = plt.subplots(1, 1)
fig.text(0.51, 0.035, r'$Generation$', ha='center', fontsize=28)
fig.text(0.07, 0.5, r'$T$', va='center', rotation='vertical', fontsize=28)
title = 'Local Temperatures of Organisms'
fig.suptitle(title)

for orgNum in range(0, numAgents):
    ax.scatter(iter_list, Beta[orgNum, :], color=[0, 0, 0], alpha=0.1)

plt.show()