#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import matplotlib

def dec2bin(num,num_digits):
    frmt = '{:0'
    frmt += str(num_digits)
    frmt += 'b}'
    return frmt.format(num)

loadfile = 'learn_evolve'
gen = 1000
motor = 'dr'

plt.rc('text', usetex=True)
font = {'family': 'serif', 'size': 15, 'serif': ['computer modern roman']}
plt.rc('font', **font)
plt.rc('legend', **{'fontsize': 16})

R = 1

Nsens = 100
sens = np.linspace(-1, 1, Nsens)
numAgents = 50

d = np.dtype([('MV', 'f8'), ('MR', 'f8'), ('CMV', 'f8'), ('CMR', 'f8')])
data = np.zeros((R, numAgents, Nsens), dtype=d)

folder = 'save/' + loadfile + '/Motor_Response_' + motor + '/gen_' + str(gen) + '/'

for sensInd in np.arange(1, Nsens):
    file = 'MR-' + 'Nsens_' + str(Nsens) + \
           '-sensInd_' + str(sensInd) + \
           '-gen_' + str(gen) + \
           '.npy'
    filename = folder + file

    data[:, :, sensInd] = np.load(filename)


fig, ax = plt.subplots(2, 2, figsize=(5, 5), sharex=False)
fig.text(0.5, 0.04, 'Sensory Activation (food angle)', ha='center', fontsize=36)
fig.text(0.04, 0.72, 'Motor Response', va='center', rotation='vertical', fontsize=36)
fig.text(0.04, 0.28, 'Motor Susceptiblity', va='center', rotation='vertical', fontsize=36)


title = 'Motor Response (dv, d$\omega$) of Foraging Community\n Generation: ' + str(gen)
fig.suptitle(title)

# dist = np.sqrt( 1 / ( np.arctanh( (sens + 1 ) / 2 ) ) - 1e-6 )  #  plot as a function of distance
theta = sens * 180
# xticks = [np.min(dist[1:-1]), 1, 2, 4, np.max(dist[1:-1])]
# xticks = [0.5, 1, 2, 4, 9]
xticks = [-180, -90, 0, 90, 180]
for iplot, name in enumerate(d.names):

    for i in range(0,50):
        x = int(dec2bin(iplot, 2)[0])
        y = int(dec2bin(iplot, 2)[1])
        ax[x, y].scatter(
            theta[1:], np.mean(data[name][:, i, 1:],  # average across repitions
                          axis=0), color=[0, 0, 0], s=30, alpha=0.1)
        # ax[x, y].set_xscale("log", nonposx='clip')
        ax[x, y].set_xticks(xticks)
        ax[x, y].get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
        # ax[x, y].set_title(name)

ax[0, 0].set_title(r'$dv$')
ax[0, 1].set_title(r'$d\omega$')
ax[1, 0].set_title(r'$\sigma^2(dv)$')
ax[1, 1].set_title(r'$\sigma^2(d\omega)$')

#
# for i in range(2):
#     for j in range(2):
#         # ax[i, j].set_xscale("log", nonposx='clip')
#         ax[i, j].set_xticks(xticks)
#         ax[i, j].xaxis.set_major_formatter(matplotlib.ticker.ScalarFormatter())
#         ax[i, j].xaxis.set_major_locator(matplotlib.ticker.MaxNLocator(integer=True))
#
# # plt.axis([0.1, 10, -0.02, 1.5*np.max(meanC)])


# plt.axis([-1, 1, -1, 1])
# plt.savefig('img/fig1b.pdf', bbox_inches='tight')
plt.show()
