#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from os import path, makedirs
# beta-1/sim-20180511-163319
# beta-10/sim-20180512-105824
# beta-0-1/sim-20180512-105719
# TODO: make these scripts take these as params
loadfiles = ['beta_experiment/beta-1/sim-20180511-163319',
             'beta_experiment/beta-10/sim-20180512-105824',
             'beta_experiment/beta-0-1/sim-20180512-105719']

saveFig = False

for loadfile in loadfiles:
    folder = 'save/' + loadfile
    # iter_gen = np.arange(0, 2000, 250)
    # iter_gen = np.append(iter_gen, 1999)
    # iter_gen = [0, 252, 504, 756, 1002, 1254, 1500, 1752, 1998]
    # iter_gen = [0, 1, 2, 5, 10, 20, 50, 100, 250, 1000, 1999,
    #             2250, 2500, 2750, 3000, 3250, 3500, 3750, 3999]
    iter_gen = [0, 3999]

    R = 5
    Nbetas = 101
    betas = 10 ** np.linspace(-1, 1, Nbetas)
    numAgents = 50
    size = 10

    C = np.zeros((R, numAgents, Nbetas, len(iter_gen)))
    Sm = np.zeros((R, numAgents, Nbetas, len(iter_gen)))
    Sp = np.zeros((R, numAgents, Nbetas, len(iter_gen)))
    F = np.zeros((R, numAgents, Nbetas, len(iter_gen)))

    print('Loading data...')
    for ii, iter in enumerate(iter_gen):
        for bind in np.arange(1, 101):
            filename = folder + '/C-S-natural/C-S-natural_' + str(iter) + '/C-S-size_' + str(size) + '-Nbetas_' + \
                       str(Nbetas) + '-bind_' + str(bind) + '.npz'
            data = np.load(filename)
            C[:, :, bind, ii] = data['C']
            Sm[:, :, bind, ii] = data['Sm']
            Sp[:, :, bind, ii] = data['Sp']
            F[:, :, bind, ii] = data['F']
    print('Done.')

    plt.rc('text', usetex=True)
    font = {'family': 'serif', 'size': 28, 'serif': ['computer modern roman']}
    plt.rc('font', **font)
    plt.rc('legend', **{'fontsize': 20})

    b = 0.8
    alpha = 0.05

    print('Generating figures...')
    for ii, iter in enumerate(iter_gen):

        fig, ax = plt.subplots(2, 2, figsize=(11, 10), sharex='col')
        fig.text(0.51, 0.035, r'$\beta$', ha='center', fontsize=28)
        # fig.text(0.005, 0.5, r'$C/N$', va='center', rotation='vertical', fontsize=28)
        title = 'Specific Heat and Susceptibility\n Generation: ' + str(iter)
        ax[0, 0].set_ylabel(r'$C/N$')
        ax[0, 1].set_ylabel(r'$\chi_M$')
        ax[1, 0].set_ylabel(r'$\chi_p$')
        ax[1, 1].set_ylabel(r'$Fitness$')
        fig.suptitle(title)

        # CHANGE THIS TO CUSTOMIZE HEIGHT OF PLOT
        # upperbound = 1.5 * np.max(np.mean(np.mean(C[:, :, :-40, :], axis=0), axis=0))
        # upperbound = np.max(np.mean(np.mean(C, axis=0)), axis=0)
        # upperbound = 0.4

        label = iter

        for numOrg in range(numAgents):
            # c = np.dot(np.random.random(), [1, 1, 1])
            # ax[0, 0].scatter(betas, np.mean(C[:, numOrg, :, ii], axis=0),
            #            color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
            #
            # ax[0, 1].scatter(betas, np.mean(Sm[:, numOrg, :, ii], axis=0),
            #               color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
            #
            # ax[1, 0].scatter(betas, np.mean(Sp[:, numOrg, :, ii], axis=0),
            #               color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
            #
            # ax[1, 1].scatter(betas, np.mean(F[:, numOrg, :, ii], axis=0),
            #                  color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

            # for rep in range(R):
            #     ax[0, 0].scatter(betas, np.multiply( betas**2, C[rep, numOrg, 1:, ii]),
            #                      color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
            #
            #     ax[0, 1].scatter(betas, Sm[rep, numOrg, 1:, ii],
            #                      color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
            #
            #     ax[1, 0].scatter(betas, Sp[rep, numOrg, 1:, ii],
            #                      color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
            #
            #     ax[1, 1].scatter(betas, F[rep, numOrg, 1:, ii],
            #                      color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

            for rep in range(R):
                ax[0, 0].scatter(betas[1:-1], C[rep, numOrg, 1:-1, ii],
                                 color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

                ax[0, 1].scatter(betas[1:-1], Sm[rep, numOrg, 1:-1, ii],
                                 color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

                ax[1, 0].scatter(betas[1:-1], Sp[rep, numOrg, 1:-1, ii],
                                 color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

                ax[1, 1].scatter(betas[1:-1], F[rep, numOrg, 1:-1, ii],
                                 color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

        # for numOrg in range(numAgents):
        #     c = np.dot(np.random.random(), [1, 1, 1])
        #     ax[0, 0].scatter(betas,np.mean(C[:, numOrg, :, ii], axis=0),
        #                color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[0, 1].scatter(betas, np.log10( np.mean(Sm[:, numOrg, :, ii], axis=0)),
        #                   color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[1, 0].scatter(betas, np.log10( np.mean(Sp[:, numOrg, :, ii], axis=0)),
        #                   color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[1, 1].scatter(betas, np.mean(F[:, numOrg, :, ii], axis=0),
        #                      color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

        # for numOrg in range(numAgents):
        #     c = np.dot(np.random.random(), [1, 1, 1])
        #     ax[0, 0].scatter(betas, np.log10(np.mean(C[:, numOrg, :, ii], axis=0)),
        #                color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[0, 1].scatter(betas, np.log10( np.multiply(np.mean(Sm[:, numOrg, :, ii], axis=0), betas)),
        #                   color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[1, 0].scatter(betas, np.log10( np.mean(Sp[:, numOrg, :, ii], axis=0)),
        #                   color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[1, 1].scatter(betas, np.mean(F[:, numOrg, :, ii], axis=0),
        #                      color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

        # for numOrg in range(numAgents):
        #     c = np.dot(np.random.random(), [1, 1, 1])
        #     ax[0, 0].scatter(betas,
        #                      np.log10(
        #                          np.multiply( np.mean(C[:, numOrg, :, ii], axis=0), np.power(betas, 2))
        #                          ),
        #                      color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[0, 1].scatter(betas,
        #                      np.log10(
        #                          np.mean(Sm[:, numOrg, :, ii], axis=0)),
        #                   color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[1, 0].scatter(betas, np.log10(
        #                                 np.multiply(
        #                                     np.mean(Sp[:, numOrg, :, ii], axis=0),
        #                                     betas
        #                                 )
        #                             ),
        #                   color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)
        #
        #     ax[1, 1].scatter(betas, np.mean(F[:, numOrg, :, ii], axis=0),
        #                      color=[0, 0, 0], s=30, alpha=alpha, marker='x', label=label)

        # ax[0, 0].set_xscale("log")

        xticks = [0.1, 0.5, 1, 2, 10]
        for i in np.arange(0, 2):
            for j in np.arange(0, 2):
                ax[i, j].set_xscale("log", nonposx='clip')
                # ax[i, j].set_yscale("log", nonposy='clip')
                ax[i, j].set_xticks(xticks)
                ax[i, j].get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())

        # plt.axis([0.1, 10, 0, upperbound])

        # leg = plt.legend(loc=2, title='Generation')
        #
        # for lh in leg.legendHandles:
        #     lh.set_alpha(1)
        #     lh.set_sizes(30)

        savefolder = folder + '/figs/C-S-natural/'
        savefilename = savefolder + 'C-S-natural-size_' + str(size) + '-Nbetas_' + \
                       str(Nbetas) + '-gen_' + str(iter) + '.png'
        if not path.exists(savefolder):
            makedirs(savefolder)

        plt.tight_layout()
        # plt.show()
        if saveFig:
            plt.savefig(savefilename, bbox_inches='tight')
            savemsg = 'Saving ' + savefilename
            print(savemsg)
        # plt.close()
        # plt.clf()
plt.show()
    # plt.pause(0.1)